# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?




data = [
	{'title': 'eu', 'content': 'ut aliquam iaculis, lacus', 'uesr_id': 1},
	{'title': 'eu,', 'content': 'Nullam', 'uesr_id': 1},
	{'title': 'aliquet', 'content': 'est tempor bibendum. Donec felis orci, adipiscing', 'uesr_id': 1},
	{'title': 'natoque', 'content': 'adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper.', 'uesr_id': 1},
	{'title': 'amet', 'content': 'luctus ut, pellentesque eget, dictum placerat, augue.', 'uesr_id': 1},
	{'title': 'erat', 'content': 'tempor diam dictum', 'uesr_id': 1},
	{'title': 'nisi.', 'content': 'amet ante. Vivamus non lorem vitae odio sagittis semper. Nam', 'uesr_id': 1},
	{'title': 'tempus', 'content': 'libero at auctor ullamcorper, nisl', 'uesr_id': 1},
	{'title': 'at', 'content': 'primis in faucibus orci luctus et ultrices posuere', 'uesr_id': 1},
	{'title': 'est,', 'content': 'Nulla semper tellus id nunc interdum feugiat. Sed nec', 'uesr_id': 1},
	{'title': 'Nulla', 'content': 'Mauris', 'uesr_id': 1},
	{'title': 'vitae,', 'content': 'et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor', 'uesr_id': 1},
	{'title': 'Curabitur', 'content': 'dapibus gravida. Aliquam', 'uesr_id': 1},
	{'title': 'nec', 'content': 'bibendum. Donec felis orci, adipiscing non, luctus sit', 'uesr_id': 1},
	{'title': 'eget,', 'content': 'Sed neque. Sed eget lacus.', 'uesr_id': 1},
	{'title': 'non', 'content': 'nunc. Quisque ornare tortor at risus. Nunc', 'uesr_id': 1},
	{'title': 'dui.', 'content': 'dictum magna. Ut tincidunt orci quis lectus. Nullam', 'uesr_id': 1},
	{'title': 'pede', 'content': 'a mi fringilla mi', 'uesr_id': 1},
	{'title': 'Sed', 'content': 'sem. Pellentesque ut ipsum', 'uesr_id': 1},
	{'title': 'dictum', 'content': 'eu neque pellentesque massa lobortis ultrices.', 'uesr_id': 1},
	{'title': 'ullamcorper', 'content': 'libero est, congue a,', 'uesr_id': 1},
	{'title': 'semper', 'content': 'Cras dictum ultricies ligula. Nullam enim. Sed nulla', 'uesr_id': 1},
	{'title': 'Aenean', 'content': 'ornare, facilisis eget,', 'uesr_id': 1},
	{'title': 'ut,', 'content': 'leo elementum sem,', 'uesr_id': 1},
	{'title': 'dictum', 'content': 'diam', 'uesr_id': 1},
	{'title': 'arcu.', 'content': 'lacus. Ut nec', 'uesr_id': 1},
	{'title': 'ac', 'content': 'Vivamus', 'uesr_id': 1},
	{'title': 'ac', 'content': 'tellus lorem', 'uesr_id': 1},
	{'title': 'semper', 'content': 'vel sapien', 'uesr_id': 1},
	{'title': 'elit.', 'content': 'augue. Sed molestie. Sed', 'uesr_id': 1},
	{'title': 'leo.', 'content': 'ullamcorper magna. Sed eu eros.', 'uesr_id': 1},
	{'title': 'tellus', 'content': 'a, aliquet vel, vulputate eu, odio. Phasellus at augue id', 'uesr_id': 1},
	{'title': 'non', 'content': 'faucibus leo, in lobortis', 'uesr_id': 1},
	{'title': 'Nullam', 'content': 'ultrices, mauris ipsum', 'uesr_id': 1},
	{'title': 'metus.', 'content': 'in', 'uesr_id': 1},
	{'title': 'et', 'content': 'a nunc. In at pede. Cras vulputate velit eu', 'uesr_id': 1},
	{'title': 'Nam', 'content': 'eu', 'uesr_id': 1},
	{'title': 'aliquet', 'content': 'laoreet ipsum. Curabitur', 'uesr_id': 1},
	{'title': 'dui', 'content': 'et, commodo', 'uesr_id': 1},
	{'title': 'elit', 'content': 'molestie', 'uesr_id': 1},
	{'title': 'velit.', 'content': 'Morbi neque tellus,', 'uesr_id': 1},
	{'title': 'lorem', 'content': 'porttitor tellus non magna. Nam ligula elit,', 'uesr_id': 1},
	{'title': 'eget', 'content': 'tempus mauris', 'uesr_id': 1},
	{'title': 'quam,', 'content': 'amet, risus. Donec', 'uesr_id': 1},
	{'title': 'dolor', 'content': 'consequat nec, mollis vitae, posuere at, velit. Cras lorem', 'uesr_id': 1},
	{'title': 'diam.', 'content': 'iaculis aliquet diam.', 'uesr_id': 1},
	{'title': 'nascetur', 'content': 'nulla. Donec non', 'uesr_id': 1},
	{'title': 'eu', 'content': 'turpis egestas. Fusce aliquet magna a neque.', 'uesr_id': 1},
	{'title': 'odio', 'content': 'Vivamus nisi. Mauris nulla. Integer urna.', 'uesr_id': 1},
	{'title': 'Cum', 'content': 'tempor', 'uesr_id': 1},
	{'title': 'Nullam', 'content': 'tincidunt congue turpis. In condimentum. Donec at', 'uesr_id': 1},
	{'title': 'aliquet', 'content': 'lacinia orci, consectetuer euismod', 'uesr_id': 1},
	{'title': 'Sed', 'content': 'non, egestas a, dui. Cras pellentesque. Sed', 'uesr_id': 1},
	{'title': 'nisi.', 'content': 'Phasellus ornare. Fusce mollis. Duis sit amet', 'uesr_id': 1},
	{'title': 'rhoncus.', 'content': 'iaculis aliquet', 'uesr_id': 1},
	{'title': 'ultricies', 'content': 'non massa non ante bibendum ullamcorper. Duis cursus, diam', 'uesr_id': 1},
	{'title': 'nec', 'content': 'sem, vitae', 'uesr_id': 1},
	{'title': 'urna', 'content': 'Maecenas ornare egestas ligula.', 'uesr_id': 1},
	{'title': 'sem', 'content': 'nunc interdum feugiat.', 'uesr_id': 1},
	{'title': 'mauris', 'content': 'nec, imperdiet nec, leo. Morbi neque tellus,', 'uesr_id': 1},
	{'title': 'risus.', 'content': 'pede, nonummy', 'uesr_id': 1},
	{'title': 'elit', 'content': 'rutrum,', 'uesr_id': 1},
	{'title': 'urna.', 'content': 'Proin mi. Aliquam gravida', 'uesr_id': 1},
	{'title': 'vel,', 'content': 'In condimentum.', 'uesr_id': 1},
	{'title': 'luctus,', 'content': 'mattis. Cras eget nisi dictum', 'uesr_id': 1},
	{'title': 'conubia', 'content': 'sapien molestie orci tincidunt adipiscing. Mauris molestie', 'uesr_id': 1},
	{'title': 'vel', 'content': 'tincidunt orci quis lectus. Nullam suscipit, est ac facilisis', 'uesr_id': 1},
	{'title': 'ac', 'content': 'lobortis tellus justo sit amet nulla. Donec non justo.', 'uesr_id': 1},
	{'title': 'ac', 'content': 'sapien, gravida non, sollicitudin a, malesuada', 'uesr_id': 1},
	{'title': 'sapien.', 'content': 'in lobortis tellus justo sit amet nulla. Donec', 'uesr_id': 1},
	{'title': 'pede,', 'content': 'accumsan convallis, ante lectus convallis est, vitae', 'uesr_id': 1},
	{'title': 'Vivamus', 'content': 'a sollicitudin orci sem eget massa.', 'uesr_id': 1},
	{'title': 'sit', 'content': 'metus. In', 'uesr_id': 1},
	{'title': 'arcu.', 'content': 'Nunc quis arcu vel quam dignissim', 'uesr_id': 1},
	{'title': 'congue', 'content': 'at augue id ante dictum cursus. Nunc mauris elit, dictum', 'uesr_id': 1},
	{'title': 'Aliquam', 'content': 'erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie', 'uesr_id': 1},
	{'title': 'cursus.', 'content': 'Duis a mi fringilla mi', 'uesr_id': 1},
	{'title': 'porttitor', 'content': 'Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum', 'uesr_id': 1},
	{'title': 'eget', 'content': 'magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna.', 'uesr_id': 1},
	{'title': 'In', 'content': 'metus. Aenean sed pede nec ante blandit viverra. Donec tempus,', 'uesr_id': 1},
	{'title': 'egestas.', 'content': 'mi', 'uesr_id': 1},
	{'title': 'pede.', 'content': 'luctus aliquet odio. Etiam ligula tortor, dictum eu,', 'uesr_id': 1},
	{'title': 'Suspendisse', 'content': 'vitae diam. Proin dolor. Nulla', 'uesr_id': 1},
	{'title': 'cursus', 'content': 'dictum magna. Ut tincidunt orci', 'uesr_id': 1},
	{'title': 'et', 'content': 'fames ac turpis egestas. Fusce', 'uesr_id': 1},
	{'title': 'neque', 'content': 'blandit at, nisi. Cum sociis natoque', 'uesr_id': 1},
	{'title': 'tellus', 'content': 'elit fermentum risus, at fringilla purus mauris a nunc.', 'uesr_id': 1},
	{'title': 'arcu.', 'content': 'turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut', 'uesr_id': 1},
	{'title': 'pede,', 'content': 'nibh. Quisque nonummy ipsum', 'uesr_id': 1},
	{'title': 'neque', 'content': 'ante ipsum primis in', 'uesr_id': 1},
	{'title': 'pretium', 'content': 'parturient', 'uesr_id': 1},
	{'title': 'tristique', 'content': 'arcu et pede. Nunc sed orci lobortis augue scelerisque', 'uesr_id': 1},
	{'title': 'nunc,', 'content': 'Donec est mauris, rhoncus id, mollis nec, cursus a, enim.', 'uesr_id': 1},
	{'title': 'ut', 'content': 'Donec nibh enim, gravida sit amet, dapibus id, blandit at,', 'uesr_id': 1},
	{'title': 'fames', 'content': 'ut', 'uesr_id': 1},
	{'title': 'Morbi', 'content': 'Quisque', 'uesr_id': 1},
	{'title': 'Donec', 'content': 'mauris, aliquam eu, accumsan sed, facilisis vitae, orci.', 'uesr_id': 1},
	{'title': 'tristique', 'content': 'vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque', 'uesr_id': 1},
	{'title': 'vel', 'content': 'a nunc. In at pede. Cras vulputate velit eu sem.', 'uesr_id': 1},
	{'title': 'Nunc', 'content': 'est tempor bibendum. Donec felis orci, adipiscing', 'uesr_id': 1}
];


data.each{ |e| Post.create(title: e[:title], body: e[:content], user: User.find(1)) }
